# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: DO init
    command: |
      brew update
      brew install nodenv node-build
      nodenv install
      node --version
      npm install
      echo 'eval "$(nodenv init -)"' | tee -a ~/.bash_profile
